---
title: "readme"
author: "mengfany"
date: "2022-12-05"
output: html_document
---

## Introduction

### What is the TRI? 
The Toxics Release Inventory (TRI) is a resource for learning about toxic chemical releases and pollution prevention activities reported by industrial and federal facilities. TRI data support informed decision-making by communities, government agencies, companies, and others. Section 313 of the Emergency Planning and Community Right-to-Know Act (EPCRA) created the TRI.

TRI tracks the management of certain toxic chemicals that may pose a threat to human health and the environment. U.S. facilities in different industry sectors must report annually how much of each chemical is released to the environment and/or managed through recycling, energy recovery and treatment. (A "release" of a chemical means that it is emitted to the air or water, or placed in some type of land disposal.)
The information submitted by facilities is compiled in the Toxics Release Inventory. TRI helps support informed decision-making by companies, government agencies, non-governmental organizations and the public.
 
### About the Project

In this project, I combine census data and TRI data to present the population distribution/density near the toxics release inventory. I also use the human health effects score to indicate how a chemical compares with others in terms of its capacity to harm human health. 

The slider on the interface shows where a compound's hazard score falls relative to all chemicals that have been ranked using this system, indicating whether it is more or less hazardous than most chemicals. Chemicals that score at 9 are significantly more hazardous (in the worst 10% of all chemicals according to this scoring system).

Users can select different population in select box to see the density of different population like white people and minorities. In this way, users could know the distribution of different group of population. 

At the same time, users could select toxic release sites with different Predominant health risks. The factories that emit different toxic pollutants will be displayed on the map in the form of points. Click on a point, and you can see the specific information of the factory.

 
### Risk main 
#### Neurotoxicity
Neurotoxicity occurs when the exposure to natural or manmade toxic substances (neurotoxicants) alters the normal activity of the nervous system. This can eventually disrupt or even kill neurons, key cells that transmit and process signals in the brain and other parts of the nervous system. Symptoms may appear immediately after exposure or be delayed. They may include limb weakness or numbness; loss of memory, vision, and/or intellect; headache; cognitive and behavioral problems; and sexual dysfunction. Individuals with certain disorders may be especially vulnerable to neurotoxicants.
 
#### Carcinogen
A carcinogen is a substance, organism or agent capable of causing cancer. Carcinogens may occur naturally in the environment (such as ultraviolet rays in sunlight and certain viruses) or may be generated by humans (such as automobile exhaust fumes and cigarette smoke). Most carcinogens work by interacting with a cell’s DNA to produce mutations.Cardiovascular toxicity includes damage to the heart due to toxin-induced electrophysiological abnormalities or/and muscle damage, as well as vascular atherosclerosis due to oxidative stress and inflammation. Taken together, these abnormalities may impair blood flow and circulation.

#### Cardiovascular toxicant
Cardiovascular toxicity includes damage to the heart due to toxin-induced electrophysiological abnormalities or/and muscle damage, as well as vascular atherosclerosis due to oxidative stress and inflammation. Taken together, these abnormalities may impair blood flow and circulation.
 
#### Respiratory toxicant
Lung toxicosis depends on the dose of toxicant delivered to lung tissues and the acute and chronic effects of toxicants. Effects can be described in terms of tissue damage and lesions as well as in terms of deficits in respiratory system function. Upper respiratory airways can be differentiated from the gas exchange region of the lung in terms of responses to toxicants and specific toxicant susceptibility.
 

